###
GET https://{{host}}:{{port}}/greets
Accept: text/plain

> {%
    client.test("Response status should be 200", () => {
        const expected = 200;

        const actual = response.status;
        client.assert(actual === expected, `Expected ${expected} but received ${actual}.`)
    });

    client.test("Response content-type should be 'text/plain'", () => {
        const expected = "text/plain";

        const actual = response.contentType.mimeType;
        client.assert(actual === expected, `Expected ${expected} but received ${actual}.`)
    });

    client.test("Response body should contain 'Hello Elysia~!'", () => {
        const expected = "Hello.Elysia!"

        const actual = response.body
        client.assert(actual === expected, `Expected ${expected} but received ${actual}.`)
    });

%}

